name: py35
dependencies:
 - python=3.5.2=0
 - pip=8.1.1=py35_0
 - pip:
   - termcolor
   - python-magic==0.4.12
   - flask
   - pygments
   - ansiconv
   - numpy
   - https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.11.0-cp35-cp35m-linux_x86_64.whl
   - sphinx==1.5.1
